### ISSUE TITLE
Add counter to Task IO splice 

### ISSUE THREAD

**Issue by vavrecan** [heiher/hev-task-system#7]
Hello,
This is implementation I did so that counter can be used with task_io_splice call.

https://github.com/heiher/hev-task-system/compare/master...vavrecan:hev-task-system:master

Usage is simple them,
```
    size_t received;
    size_t sent;
    hev_task_io_splice_counter (cfd, cfd, fd, fd, 8192, task_io_yielder, self, &sent, &received);
```

Let me know if you find it useful or if it makes sense to integrate, I can make PR then. 
Thank you

**Comment by heiher** [comment]
Thanks for sharing your implementation. Sorry, I have no plans to integrate it into the generic `io splice` at the moment. However, I'll write a customized example that override the generic implementation in hev-socks5-server to share with you.
