### ISSUE TITLE
Memory pool using lru algorithm

### ISSUE THREAD

**Issue by cuicanju** [heiher/hev-task-system#8]
May I ask why your memory pool implementation uses the LRU algorithm? Where is the specific role reflected?

**Comment by heiher** [comment]
`HevMemoryAllocatorSlice` has caching capability, using the LRU algorithm to evict the least recently used size of memory blocks.

**Comment by cuicanju** [comment]
I mean does this really improve performance? Because I have almost never seen the lru algorithm in memory pool projects
